Add images to team section
JIITODC/trident pull request #37
Opened 2020-03-17 11:50 UTC by eldraco19

Fixes: #36

2020-03-17 13:45 UTC, karandevtyagi commented
@eldraco19 good work.Just reduce the space between heading and the content of page in every page which has excess space.This will make it good on phone as well.

![Issue3](https://user-images.githubusercontent.com/40595692/76862159-a7984480-6883-11ea-8426-b6e8f3fcd8ab.PNG)

2020-03-17 14:57 UTC, eldraco19 commented
@karandevtyagi done!

2020-03-17 15:39 UTC, karandevtyagi commented
@eldraco19 Toggle to mobile devices in your dev tools and look at the extra spaces in complete website and remove them.Plus add credit to yourself in footer or add github repo link so that you can show this in future to someone or in resume if required.

2020-03-17 16:54 UTC, eldraco19 commented
@karandevtyagi on Desktop it looks fine, on mobile I tried to reduce as much as I can without affecting other components.

**Old**
![old](https://user-images.githubusercontent.com/41536589/76880623-f18e2400-689d-11ea-8bfa-8b05a0ccaa1e.png)

**New**
![new](https://user-images.githubusercontent.com/41536589/76880653-0074d680-689e-11ea-8694-8f00804ad09a.png)

2020-03-17 19:38 UTC, rexagod requested changes

2020-03-17 19:38 UTC, rexagod commented on index.html
> +                <li><a href="diversity.html"style="font-weight: bold;">Divesity and Inclusion</a></li>
```suggestion
                <li><a href="diversity.html"style="font-weight: bold;">Diversity and Inclusion</a></li>
```

2020-03-17 20:01 UTC, rexagod commented
https://github.com/JIITODC/trident/blob/ec2f74e354b4e0d6fcd8d9af031f33850184180c/index.html#L525-L536

Also this?

2020-03-17 20:32 UTC, rexagod requested changes
PTAL

2020-03-17 20:32 UTC, rexagod commented on about.html
> +                <p class="author mb-0">Pranshu Shrivastava</p>
```suggestion
                <p class="author mb-0">Pranshu Srivastava</p>
```

2020-03-17 20:32 UTC, rexagod commented on about.html
> +                <p class="text-muted mb-4">Tech and Management Head</p>
```suggestion
                <p class="text-muted mb-4">Technology and Management Head</p>
```

2020-03-18 00:28 UTC, karandevtyagi commented
About Event in footer of judge and tracks page require change.

2020-03-18 01:24 UTC, rexagod commented
ping @eldraco19 ==> https://github.com/JIITODC/trident/pull/37#issuecomment-600270043

2020-03-18 07:51 UTC, eldraco19 commented
@karandevtyagi footer fixed in all pages with social links and quick links(they were missing in some pages)

@rexagod Colorlib->JODC done!

2020-03-18 11:29 UTC, karandevtyagi commented
@eldraco19 JODC in footer still leads in colorlib.

2020-03-18 11:30 UTC, rexagod requested changes
Could you also remove the `colorlib` comments?

2020-03-18 11:30 UTC, rexagod commented on venue.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 11:30 UTC, rexagod commented on tracks.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="hhttps://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 11:30 UTC, rexagod commented on judges.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 11:30 UTC, rexagod commented on diversity.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 11:30 UTC, rexagod commented on code-of-conduct.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 11:30 UTC, rexagod commented on about.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 12:22 UTC, Ankk98 commented
@rexagod @eldraco19 
Have a look here: [Colorlib Licence](https://colorlib.com/wp/licence/ )
"You are not allowed to remove the copyright credit from the footer."
So, add credits to both: colorlib and jodc.

2020-03-18 12:24 UTC, Ankk98 commented
@rexagod @karandevtyagi 
Suggestion: 
I don't think we need to make another discord server for this. Instead add a channel in existing server and use the same. This will be more convinient.

2020-03-18 12:27 UTC, Ankk98 commented
@eldraco19 @rexagod @karandevtyagi  @VARoDeK 
We need to add term and conditions also. Especially the one saying that all final rights remain with the organisers.

2020-03-18 12:30 UTC, Ankk98 commented
@eldraco19 
Registration button do not work: Add something saying registration will start soon.

2020-03-18 12:43 UTC, Ankk98 requested changes
Make changes along the line of suggestions.

2020-03-18 12:43 UTC, Ankk98 commented on about.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
```suggestion
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a> and <a href="https://github.com/JIITODC" target="_blank" >JODC</a>
```

2020-03-18 12:43 UTC, Ankk98 commented on about.html
> +              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https:
Something like this would be better.

2020-03-18 14:41 UTC, koderjoker requested changes
Suggestions: 
1. Use `align-content: flex-end` on the divs with the class "row" containing headings (About, Judges) to improve the awkward spacing issue
2. Deleting the "About" heading from the main page (index.html) improves the look of the website since it doesn't seem to be necessary, and it sticks out like a sore thumb compared to the other subheadings which have a white font and a red underline

2020-03-18 14:46 UTC, eldraco19 commented
@Ankk98 added a popup in the registration button.
@rexagod Added both colorlib and JODC in the footer.

2020-03-18 15:04 UTC, karandevtyagi commented
> Suggestions:
> 
> 1. Use `align-content: flex-end` on the divs with the class "row" containing headings (About, Judges) to improve the awkward spacing issue
> 2. Deleting the "About" heading from the main page (index.html) improves the look of the website since it doesn't seem to be necessary, and it sticks out like a sore thumb compared to the other subheadings which have a white font and a red underline

- [ ] Add t&c

@rexagod @eldraco19 I think after this we can Squash and merge this PR and can release Trident v1.0

2020-03-18 15:15 UTC, Ankk98 commented
@karandevtyagi
I think this would be v0.91 or something.
There are still some minor issues that we need to fix. I will add some of them as issues. Then we should be showing the website to others (beta test).
After that if we find it complete, then it should be v1(release).

2020-03-18 15:29 UTC, karandevtyagi commented
PiedPiper got it.

2020-03-18 15:46 UTC, Ankk98 commented
@eldraco19 
Kindly fix the inconsistent spacing between where-timeline , register-about etc.

2020-03-18 15:49 UTC, Ankk98 commented
@eldraco19 @rexagod 
About page and diversity and inclusion page are sideways scrollable/horizontally which is undesired.
Kindly fix it.

2020-03-18 23:14 UTC, eldraco19 commented
@Ankk98 horizontal scroll fixed

2020-03-18 23:15 UTC, eldraco19 commented
resolves #43 
resolves #45  
resolves #46 
resolves  #40 
resolves  #38  
resolves #47

2020-03-19 01:25 UTC, rexagod commented
There's a spacing issue between the map and footer on venue page. PTAL.

2020-03-19 05:25 UTC, Ankk98 commented
@eldraco19 
- [ ] Add a notice in the 'when' section that event has been postponed due to COVID-19 pandemic.
- [ ] Add how to reach jiit-128 through the cab(Like dest address me exactly kya type karne se aayega) and nearest metro stations of all the 3 lines.

I think after these we can go for a beta test @karandevtyagi @rexagod .

2020-03-19 05:40 UTC, Ankurk99 commented
@Ankk98 on it.

2020-03-19 06:32 UTC, Ankurk99 commented
Done #49

2020-03-19 08:42 UTC, eldraco19 commented
@rexagod spacing issue in venue page fixed

2020-03-19 08:44 UTC, eldraco19 commented
I guess we should merge this now. I am leaving rest of the CSS issues for @JIITODC/trident-volunteers
I will add the TnC page in another PR.

2020-03-19 09:34 UTC, karandevtyagi approved these changes

2020-03-19 09:49 UTC, Ankk98 approved these changes

2020-03-19 10:23 UTC, merged

2020-03-19 11:51 UTC, rexagod commented
@eldraco19 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥