add 'how to reach' and postponed notice
JIITODC/trident pull request #49
Opened 2020-03-19 06:32 UTC by Ankurk99

Fixes:

2020-03-19 07:54 UTC, Ankk98 commented
Replace How to reach to venue page.
Also you have mentioned aqua in place of blue line. Fix it.
@Ankurk99

2020-03-19 07:56 UTC, Ankk98 commented
@Ankurk99 Check if changing colour of to be announced make it better or not.

2020-03-21 04:06 UTC, Ankk98 commented
Fix merge conflicts.

2020-03-24 07:45 UTC, Ankk98 commented
@Ankurk99 Any progress?

2020-03-24 11:44 UTC, Ankurk99 commented
Done

2020-03-24 11:55 UTC, Ankurk99 commented
> Replace How to reach to venue page.
> Also you have mentioned aqua in place of blue line. Fix it.
> @Ankurk99
It's on aqua line(comes under noida metro NMRC).

2020-03-24 11:59 UTC, Ankurk99 commented
> @Ankurk99 Check if changing colour of to be announced make it better or not.

Done

2020-03-24 12:25 UTC, Ankurk99 commented
@Ankk98 Done all the changes. PTAL

2020-03-24 12:47 UTC, Ankk98 commented
@Ankurk99 Needs some fixes, ptal at image below.
![trident-bug](https://user-images.githubusercontent.com/24476799/77426995-95765300-6dfb-11ea-8549-8767ac2141ee.png)

2020-03-24 12:53 UTC, Ankurk99 commented
> @Ankurk99 Needs some fixes, ptal at image below.
> ![trident-bug](https://user-images.githubusercontent.com/24476799/77426995-95765300-6dfb-11ea-8549-8767ac2141ee.png)

Yes, the commit crashed some of the content. On it.

2020-03-24 13:25 UTC, Ankurk99 commented
Done. PTAL

2020-03-24 14:44 UTC, Ankk98 commented
1. [ ] Fix footer
2. [ ] Replace this line with - 
"New Delhi/Ghaziabad/Faridabad Nearest Metro Station(Magenta Line or Aqua-Line - Noida Metro)"
 -> "New Delhi/Ghaziabad/Faridabad/Gurugram Nearest Metro Station(Magenta Line or Blue line)"

 @Ankurk99  Check preview Here: [preview](https://deploy-preview-49--tridentjodc.netlify.com/venue.html)

![screenshot](https://user-images.githubusercontent.com/24476799/77437629-e3df1e00-6e0a-11ea-9292-0b168877392e.png)

2020-03-24 16:11 UTC, Ankurk99 commented
@Ankk98 PTAL

2020-03-24 16:30 UTC, Ankk98 commented
Looks good to me. @rexagod review and merge.

2020-03-24 21:54 UTC, rexagod requested changes

2020-03-24 21:54 UTC, rexagod commented on css/style.css
> +>>>>>>> parent of 5882d54... add 'How to reach' to 'Venue' page
A merge conflict was `add`ed and `commit`ed here. Please fix this.

2020-03-27 21:01 UTC, Ankurk99 commented
@rexagod  PTAL.

2020-03-28 07:32 UTC, rexagod approved these changes

2020-03-28 07:32 UTC, merged